name: provider_test
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.7
  geolocator: ^10.1.0
  flutter_bloc: ^8.1.3
  geocoding: ^2.1.1
  google_fonts: ^6.1.0
  dropdown_button2: ^2.3.9
  stylish_bottom_bar: ^1.1.1
  curved_navigation_bar: ^1.0.6
  google_nav_bar: ^5.0.7
  line_icons: ^2.0.3
  characters: ^1.3.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  google_sign_in: ^6.1.6
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.2
  permission_handler: ^11.1.0
  provider: ^6.1.1
  flutter_native_splash: ^2.4.4
  flutter_launcher_icons: ^0.14.3
  order_tracker_zen: ^1.0.0+4
  order_tracker: ^0.0.2
  mobkit_dashed_border: ^0.0.8
  quickalert: ^1.1.0
  easy_stepper: ^0.8.5+1
  enhance_stepper: ^1.0.2
  timeline_tile: ^2.0.0
  expandable: ^5.0.1
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  path: ^1.8.3
  ionicons: ^0.2.2
  eva_icons_flutter: ^3.1.0
  lucide_icons_flutter: ^3.0.0
  go_router: ^15.1.2
  go_transitions: ^0.8.1
  
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/courier.png
    - assets/images/ksa_logo.png
  fonts:
    - family: KOSans-Medium
      fonts:
        - asset: assets/fonts/KOSans-Medium.otf
    - family: IBMPlexSansArabic
      fonts:
        - asset: assets/fonts/IBMPlexSansArabic.ttf
    - family: GE
      fonts:
        - asset: assets/fonts/GE.otf
    - family: Dubai-Regular
      fonts:
        - asset: assets/fonts/Dubai-Regular.ttf
        

flutter_native_splash:
  color: "#FBF8EF"
  image: assets/images/logo.png
  android: true
  ios: true
  web: true
  fullscreen: true
  android_12:
    image: assets/images/logo.png
    icon_background_color: "#FBF8EF"
