// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCKay78a9Om61R6fs_liLIOjipATO8Cx0',
    appId: '1:187236265267:web:1b96aafca4dbae2107e246',
    messagingSenderId: '187236265267',
    projectId: 'ontex-v1',
    authDomain: 'ontex-v1.firebaseapp.com',
    storageBucket: 'ontex-v1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhsrQu3KlZeczJ0lBLxe22syJXCS_5XwE',
    appId: '1:187236265267:android:345148934ed9b8aa07e246',
    messagingSenderId: '187236265267',
    projectId: 'ontex-v1',
    storageBucket: 'ontex-v1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDvSu4FySifT8eATMUYHPXn8hDuCvwkdY',
    appId: '1:187236265267:ios:99cf48df8892883e07e246',
    messagingSenderId: '187236265267',
    projectId: 'ontex-v1',
    storageBucket: 'ontex-v1.firebasestorage.app',
    iosBundleId: 'com.example.providerTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDvSu4FySifT8eATMUYHPXn8hDuCvwkdY',
    appId: '1:187236265267:ios:99cf48df8892883e07e246',
    messagingSenderId: '187236265267',
    projectId: 'ontex-v1',
    storageBucket: 'ontex-v1.firebasestorage.app',
    iosBundleId: 'com.example.providerTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCKay78a9Om61R6fs_liLIOjipATO8Cx0',
    appId: '1:187236265267:web:b6ce2128fef1a94a07e246',
    messagingSenderId: '187236265267',
    projectId: 'ontex-v1',
    authDomain: 'ontex-v1.firebaseapp.com',
    storageBucket: 'ontex-v1.firebasestorage.app',
  );
}
